---
cluster_name: "obs-central-apr"
VPC_ID: "vpc-0a59355eac69c9395
SUBNET_ID: "subnet-0a9d7006b9e02e8b2"
instance_type: "t3.medium"
keypair: "platform_kp"
volume_size: "30"
domain: platform.vee.codes
