---
cluster_name: "obs-central-apr"
VPC_ID: "vpc-007b759070fc3be58"
SUBNET_ID: "subnet-0d9bcb18af9579c6d"
instance_type: "t3.medium"
keypair: "platform_kp"
volume_size: "30"
domain: platform.vee.codes
