apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "obs-central-apr"
  environment:
    cluster_type: ec2
    domain: platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: staging
    public_ip: 50.19.237.246
  annotations:
    github.com/project-slug: veecode-homolog/obs-central-apr
    infracost/project: obs-central-apr
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml,infracost.yml
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$50.19.237.246 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$50.19.237.246:~/.kube/config ~/.kube/config-obs-central-apr\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"50.19.237.246\")' -i ~/.kube/config-obs-central-apr\n  export KUBECONFIG=~/.kube/config-obs-central-apr\n  kubectl get pods -A\n"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
